### ISSUE TITLE
Plugin tab does not show in AndroidStudio

### ISSUE THREAD

**Issue by byunlee** [alessandro-caldonazzi/UMLGenerator#8]
Although on the plugin page it says it is compatible with Android Studio, I do not see the 'UML Generator' tab.

**Comment by CaroBre** [comment]
I discovered the same issue. Do you have any solution for this?

**Comment by alessandro-caldonazzi** [comment]
@CaroBre @byunlee 
Apologies for not doing this sooner, I have solved the problem on android studio. 
I am publishing the new version on jetbrains, this may take a few days, in the meantime you can[ download the new release](https://github.com/alessandro-caldonazzi/UMLGenerator/releases/tag/0.1.7) and install it manually, like this...
![Xe2Pl](https://user-images.githubusercontent.com/40608955/112145719-fedd9d00-8bda-11eb-95b0-1135ff3e1e6f.png)

_Note, however, that if you install the plugin manually, you may miss future updates._
